[versions]
jacoco = "0.8.11"
kord = "0.14.0"
kotlin = "2.0.0"
ktor = "2.3.11"
mockk = "1.13.11"
slf4j = "2.0.13"
sonarqube = "4.4.1.3373"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-voice = { module = "dev.kord:kord-voice", version.ref = "kord" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
