[versions]
jacoco = "0.8.12"
kord = "0.15.0"
kotlin = "2.1.10"
ktor = "3.1.0"
mockk = "1.13.16"
slf4j = "2.0.16"
sonarqube = "6.0.1.5171"
kotlin-coroutines-test = "1.10.1"
koin = "4.0.2"
serialization = "1.8.0"
lavaplayer = "2.2.3"
lavaplayer-youtube = "1.13.0"
lavaplayer-lavasrc = "4.6.0"
idea-ext = "1.1.8"
junit-parametized = "5.12.0"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-kotlin-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-core-voice = { module = "dev.kord:kord-core-voice", version.ref = "kord"}
kord-voice = { module = "dev.kord:kord-voice", version.ref = "kord" }
kord-common = { module = "dev.kord:kord-common", version.ref = "kord" }
kord-rest = { module = "dev.kord:kord-rest", version.ref = "kord" }
kord-gateway = { module = "dev.kord:kord-gateway", version.ref = "kord" }
lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:v2", version.ref = "lavaplayer-youtube"}
lavaplayer-lavasrc = { module = "com.github.topi314.lavasrc:lavasrc", version.ref = "lavaplayer-lavasrc" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref="kotlin-coroutines-test" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
junit-parametrized = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-parametized" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
idea-ext = {id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext"}
